name: nbascrapy
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=20.3.0
  - automat=20.2.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cffi=1.14.4
  - constantly=15.1.0
  - cryptography=3.3.1
  - cssselect=1.1.0
  - decorator=4.4.2
  - hyperlink=20.0.1
  - icu=58.2
  - idna=2.10
  - incremental=17.5.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - itemadapter=0.2.0
  - jedi=0.17.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.6.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.6.0
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.1.5
  - parsel=1.5.2
  - parso=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - pluggy=0.13.1
  - prompt-toolkit=3.0.8
  - protego=0.1.16
  - ptyprocess=0.6.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pygments=2.7.3
  - pyhamcrest=2.0.2
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pytest=6.2.1
  - pytest-runner=5.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pytz=2020.4
  - pyzmq=20.0.0
  - queuelib=1.5.0
  - readline=8.0
  - scrapy=2.4.1
  - service_identity=18.1.0
  - setuptools=51.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - traitlets=5.0.5
  - twisted=20.3.0
  - w3lib=1.21.0
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=5.2.0
  - pip:
    - jsonlines==1.2.0
