name: nbascrapy
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - automat=0.8.0
  - backcall=0.2.0
  - bcrypt=3.1.7
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.1
  - constantly=15.1.0
  - cryptography=2.9.2
  - cssselect=1.1.0
  - decorator=4.4.2
  - hyperlink=19.0.0
  - icu=58.2
  - idna=2.10
  - incremental=17.5.0
  - iniconfig=1.0.1
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.5.2
  - more-itertools=8.4.0
  - ncurses=6.2
  - openssl=1.1.1g
  - packaging=20.4
  - parsel=1.5.2
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - pluggy=0.13.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - py=1.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pygments=2.6.1
  - pyhamcrest=2.0.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pytest=6.0.1
  - pytest-runner=5.2
  - python=3.8.5
  - python-dateutil=2.8.1
  - pyzmq=19.0.1
  - queuelib=1.5.0
  - readline=8.0
  - scrapy=1.6.0
  - service_identity=18.1.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - twisted=20.3.0
  - w3lib=1.21.0
  - wcwidth=0.2.5
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.7.1
  - pip:
      - jsonlines==1.2.0
